### ISSUE TITLE
Should accessible name for input type image use fallback accessible name from browser?

### ISSUE THREAD

**Issue by mraccess77** [act-rules/act-rules.github.io#1054] opened 2019-12-03 15:03 UTC
The Image button rule indicates image button's without explicit accessible name fail -- but AAM spec says browsers may assign name of "submit".     I personally agree that we should fail image buttons without an explicit name -- but most browsers except for Edge seem to assign "submit" to the name.  We should probably discuss this issue to make sure we have a full discussion.   An image button name of "submit" doesn't really say much about the real purpose of a button -- so even if there is fallback content from the browser I don't think it should be relied upon.

https://w3c.github.io/html-aam/#input-type-image

https://github.com/act-rules/act-rules.github.io/pull/1033/files#diff-f03199bebd54cfff8f9c83689c951665

**Comment by Jym77** [comment] 2019-12-10 09:58
This looks like a duplicate of #1057.
(actually, #1057 is probably the duplicate being opened later, but given that it has more details and discussion, I'm closing this one).
Feel free to reopen if you think this is different.

**Closed by Jym77** 2019-12-10 09:58 UTC
