### ISSUE TITLE
Show proper a11y issues in duplicate ID rule [3ea0c8]

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1181] opened 2020-02-20 15:29 UTC
The examples all use `div` elements, which are not known to cause accessibility problems. It would be better to have known accessibility problems as failure examples for this rule.

**Comment by Jym77** [comment] 2020-03-09 11:57
Is this a duplicate of #1212 ?

**Closed** 2020-05-01 07:30 UTC
