### ISSUE TITLE
Updating the new website some more

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#476] opened 2019-04-15 08:23 UTC
>**Note: (from Jey) I am ticking items I have done & merged**

## Navigation

- [x] Change the name from "ACT RULES CG" to "ACT-Rules Community"
  - [x] Remove its underline
  - [x] Make it look like it isn't just badly wrapped text
- [x] Move the "A community of...", the logos and the EU stuff and a link to the license into an actual page footer, not in the top of the navbar
- [ ] Reorganise the menu:
  - Rules
  - Implementations
  - How to Contribute
  - Documentation
  - About Us
  - Github Repository
  - Move glossary under Documentation
  - Collapse the subsections (see the nav on pattern-library.dequelabs.com/ for an example)
- [x] Don't uppercase menu items, it's hard to read
- [x] Don't show the "collapse menu" button on high resolution (>1280)
- [x] Rename: "DEFINITION OF "DONE" 1.0" to "Definition of Done"
- [ ] Don't scroll the nav after loading a page, it's jarring
- [x] Make the nav collaps button more subtle, have a look at what JIRA did in their design. It hides the button when the thing is open, only showing it on hover/focus, has the button sitting on a line with a color, indicating that there's a menu there to be opened, and changes icons once its open.
- [x] Don't put the logo in the scrollable area, it's small enough that we don't need it to

## Main body

- [x] Make the whitespace above and below the h1 relative to the screen height. That size is fine for a large screen, not for a small one. Same for the other headings, too much whitespace for a small screen.

## Contribute page

- [x] The "Learn more about how to join WCAG-ACT-RULES-CG" button doesn't work
- [x] Join the group links are wrong.

## Rules page

- [x] Don't include the rule count in the h1. It's not important
- [x] Remove the authors column, not important
- [x] Don't upppercase success criterion
- [x] Use the actual SC title, rather than "WCAG2:NAME-ROLE-VALUE", also not uppercase it
- [x] Don't do the outline on hover, it implies that you can interact with something
- [x] Put the atomic in a list under the description rather than in a column that doesn't even fit the ID
- [x] Use the atomic rule titles rather than their IDs
- [x] ~~Remove the numbering. If we use numbers, people might start refering to the numbers, we don't want that.~~ - @WilcoFiers - Keeping this, we want to know how many rules we have, otherwise we cannot keep track, given we are removing total count on the heading.
- [x] Show the number of implementations for each rule (e.g. Implementations: 3)

## Glossary page

- [x] Don't put the key in the heading, there's already a "key: foo" below it
- [x] As before, no numbering, no hover outline
- [x] Remove indentation from "Used in rules" section after it wraps, so that it aligns with the text above it.
- ~~[x] Change H2 headings in definitions to H3s (this is not valid)~~
- [x] Add underlines to links, it fails WCAG
- [x] Remove underline from the key as it makes it look like a link. Use some other style, like a Courier New font or something.
- [x] Let the glossary title flow above the "used in rules" list, instead of wrap for it, makes them look less separate
- [x] Use a list for the Used in rules list, WCAG issue. Don't underline them if they are in this list.
- [x] In places where we're using URLs for link text, replace them with a descriptive title

**Comment by kasperisager** [comment] 2019-04-15 12:11
Also, the URLs are now completely random making them even more unstable than previously. What's perhaps worse, the randomness is seeded by the absolute path of each rule file, making the URLs both random _and_ tied to the path of a given rule.

**Comment by WilcoFiers** [comment] 2019-04-15 14:45
- [ ] Include the randomised IDs in the frontmatter, so that they become static
- [ ] Resolve the problem where the right column in the rules page overflows the main content.
- [ ] Don't make the footer sticky in low height resolutions

**Comment by WilcoFiers** [comment] 2019-04-15 19:52
- [ ] At lower resolutions, the right side of the content of the following page is clipped: https://act-rules.github.io/pages/implementations/reporting/

**Comment by kasperisager** [comment] 2019-04-16 07:24
Protocols are also missing from all URLs in https://act-rules.github.io/testcases.json.

**Comment by Brynanders** [comment] 2019-04-16 08:19
Wilco has already mentioned this along with myself and Emma but I thought I would show you what the issue is with no responsive content when zoomed in.
![image](https://user-images.githubusercontent.com/37368581/56193338-4e4ae400-6028-11e9-8539-cd3c18332cdb.png)
1600 x 900 zoomed in 300%

**Comment by Brynanders** [comment] 2019-04-16 08:28
I also noticed that the favicon is still the "aXe" style logo. P{icky perhaps and equally not a priority ahead of the actual accessibility issues affecting the site but still there were some pretty strong feelings about the logo so I think the favicon should be removed until we have an agreed upon design.

**Comment by annethyme** [comment] 2019-04-23 11:23
- [ ] Make sure links in blocks of text (e.g. in the Glossary, https://act-rules.github.io/glossary/#accessible-name) stand out according to [Technique G183](https://www.w3.org/TR/WCAG20-TECHS/G183.html), by either: 
- making the links underline/bold/something
- ensuring a 3:1 contrast to surrounding text AND making the links underline/bold/something on hover and focus

Easiest thing would be to give them same styling as the links in the rules, e.g.: https://act-rules.github.io/rules/5f99a7

**Comment by annethyme** [comment] 2019-05-03 08:54
- [ ] When linking to input rules from the composite rule, show the name of the rule instead of the file name: 
![Screenshot 2019-05-03 at 10 52 30](https://user-images.githubusercontent.com/15611692/57127791-c12abd80-6d91-11e9-87b2-684bbff352c1.png)

**Comment by annethyme** [comment] 2019-05-03 11:40
- [ ] Can we get the frontmatter stuff into the actual rule part of the rule? I seriously couldn't find the test aspects out there at the far right, that is usually reserved for "related content", not important context: 

![Screenshot 2019-05-03 at 13 38 37](https://user-images.githubusercontent.com/15611692/57135261-0c9c9600-6da9-11e9-8443-c80868c7274d.png)

**Comment by nitedog** [comment] 2019-05-06 17:05
@skotkjerra and I are working on an analysis of the website design:
- https://github.com/act-rules/act-rules.github.io/wiki/%5BDRAFT%5D-CG-Site-Redesign

**Comment by jkodu** [comment] 2019-05-14 12:45
[ ] - When a definition has reference to another definition, they do not get linked up at the moment in referenced glossary.

**Comment by kasperisager** [comment] 2019-05-15 09:11
The hamburger menu overlaps headings in some cases:

<img width="405" alt="image" src="https://user-images.githubusercontent.com/1174718/57763661-22438100-7702-11e9-87fe-2e07b289828c.png">

**Comment by kasperisager** [comment] 2019-05-16 06:53
Some stray pages are showing up in the menu:

<img width="178" alt="image" src="https://user-images.githubusercontent.com/1174718/57832502-1c0fdc00-77b8-11e9-9809-936cb478de20.png">

**Comment by jkodu** [comment] 2019-06-25 12:39
Closing this issue. Have created #623 for pending items.

**Closed by jkodu** 2019-06-25 12:39 UTC
