### ISSUE TITLE
Rewriting example descriptions

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#1030] opened 2019-11-21 11:48 UTC
The feedback we got from AG on the page-has-title rule was largely focused on the description of the examples. Looking back, we have not paid all that much attention to the example description. This has lead to some inconsistencies, and issues with clarity.

I suspect that in order for us to get rules published on the W3C, the example descriptions have to be improved. I've put in a PR that shows what direction I think this should go:

https://github.com/act-rules/act-rules.github.io/pull/1028/files

Unfortunately, this is going to be quite a lot of work, but I think this is going to be essential for having the W3C take over these rules. Let's figure out a way to get this done.

**Comment by Jym77** [comment] 2019-11-26 10:33
I fully agree with improving examples descriptions. We should also take the opportunity to try and write guidelines on what these should be (#834).

**Comment by jkodu** [comment] 2019-12-10 10:30
Duplicate of https://github.com/act-rules/act-rules.github.io/issues/834

**Closed by jkodu** 2019-12-10 10:30 UTC
