### ISSUE TITLE
Clarification of SC for Orientation of the page is not restricted using CSS transform property

### ISSUE THREAD

**Issue by kengdoj** [act-rules/act-rules.github.io#1608] opened 2021-05-12 23:12 UTC
[Rule Id: b33eff](https://act-rules.github.io/rules/b33eff)

My understanding of SC 1.3.4 Orientation is that the element must be oriented correctly when opened in landscape and portrait. [F97](https://www.w3.org/WAI/WCAG21/Techniques/failures/F97) and [F100](https://www.w3.org/WAI/WCAG21/Techniques/failures/F100) test by opening the content.

The rule's Expectation describes the element must orient correctly during a change of orientation (when the device is being rotated). Where is this supported in the SC?

**Comment by daniel-montalvo** [comment] 2021-05-28 09:24
> [Rule Id: b33eff](https://act-rules.github.io/rules/b33eff)
> 
> My understanding of SC 1.3.4 Orientation is that the element must be oriented correctly when opened in landscape and portrait. [F97](https://www.w3.org/WAI/WCAG21/Techniques/failures/F97) and [F100](https://www.w3.org/WAI/WCAG21/Techniques/failures/F100) test by opening the content.
> 
> The rule's Expectation describes the element must orient correctly during a change of orientation (when the device is being rotated). Where is this supported in the SC?

I would support your appreciation, @kengdoj that this expectation needs to be revisited. I have trouble to understand what it tries to communicate, apart from what you just said above.

On the other hand, I do think this rule is valid and I would say we should accept it once we discuss the expectation. According to your understanding of the SC, if you effectively restrict the orientation, you are not allowing the user to view the contents in their preferred orientation. That would be already a failure, irrespective of whether there is an orientation change while the content is loaded.

**Comment by patrickhlauke** [comment] 2021-06-10 21:39
both on opening, and on change. whether the user starts in a particular orientation, or they decide for whatever reason to change orientation after content loaded, it must not door-slam them (e.g. "please turn your phone to portrait to view this content")

**Comment by bruce-usab** [comment] 2021-06-14 16:33
> Where is this supported in the SC?

It is a plain reading of <q>Content does not restrict its view and operation to a single display orientation</q>

I agree that the two documented failures (F97 and F100) do not address the on-change requirement implicit in the SC text.  We could use another failure technique, as well a sufficient technique.

**Comment by patrickhlauke** [comment] 2021-06-14 17:35
wondering about the scenario where rotating a page after loading results in a "you rotated the device ... please reload the page to adapt it correctly" type message. unusual, but arguably this would pass in my view (if it was clear to the user what to do, no data was lost, etc). seems more of an edge case,

**Comment by Jym77** [comment] 2021-06-17 12:03
I think that the note might be a bit misleading in mentioning changing the orientation. For all the Failed Examples, the problem does exists when the page is open in the "wrong" orientation. The media query that triggers it does not need the change of orientation to happen while the page is opened, so the problem is here also on opening.

(trying Failed Example 1 in Portrait orientation actually doesn't display anything which I assume is due to the rotation sending the content out of the viewport because it must be centered on the corner of the page or something… We may want to update that example (and possibly others) to bring the content on the page… OTOH, this is clearly a page that doesn't let people see it in Portrait orientation 😄 )

**Comment by WilcoFiers** [comment] 2021-11-16 10:20
@kengdoj Can you open an issue for this in the WCAG repo instead? This doesn't seem like an ACT specific question. Because of that, I'm going to close the issue here.

**Closed by WilcoFiers** 2021-11-16 10:20 UTC
