### ISSUE TITLE
Rule: "id attribute value is unique" should explain why further testing is needed (3ea0c8)

### ISSUE THREAD

**Issue by moekraft** [act-rules/act-rules.github.io#1079] opened 2019-12-12 14:07 UTC
In outcome mappings, it states that passed outcomes require further testing. I don't see why. Please add an explicit statement as to why this is necessary.

**Comment by Jym77** [comment] 2019-12-13 12:54
The "further testing is needed" part of the accessibility requirements refers to the full SC. In that case, 4.1.1: Parsing.

If `id` attribute are uniques but, say, some elements contain duplicate attribute, then this rules passes but the SC still fails.

Thus, if the rule passes, one still need further testing to decide whether SC 4.1.1 passes or not.

**Comment by jkodu** [comment] 2020-01-21 10:27
Similar issue https://github.com/act-rules/act-rules.github.io/issues/1078

**Comment by jkodu** [comment] 2020-02-04 10:49
Duplicate of https://github.com/w3c/wcag-act/issues/426

**Closed by jkodu** 2020-02-04 10:49 UTC
Labels: Agenda item
