### ISSUE TITLE
"Filename is valid accessible name" should be limited to `img` and `input[type=image]` (9eb3f6)

### ISSUE THREAD

**Issue by WilcoFiers** [act-rules/act-rules.github.io#622] opened 2019-06-25 11:59 UTC
The following should not be applicable:

```html
<div src="foo" role="img" aria-label="foo"></div>
```

**Comment by kasperisager** [comment] 2019-06-25 13:33
Duplicate of https://github.com/act-rules/act-rules.github.io/issues/465

**Comment by jkodu** [comment] 2019-07-03 11:57
Duplicate issue

**Closed by jkodu** 2019-07-03 11:57 UTC
Labels: Rule
