### ISSUE TITLE
Add techniques and WAI-ARIA as accessibility requirements

### ISSUE THREAD

**Issue by annethyme** [act-rules/act-rules.github.io#516] opened 2019-05-07 12:03 UTC
When updating the template of the published rules to match the newest version of the ACT Rules Format we did not move techniques from the Background section to the Accessibility Requirements mapping, even though this is a possibility now. 

I suggest we at one point go through all rules and see, if there is a fail-on-fail relationship between the rules and any techniques listed in the Background section. 
If the answer is "yes", we move the technique into the accessibility requirements section and remove it from the Background.

**Comment by Jym77** [comment] 2019-12-13 14:35
See also #1011.

**Comment by jkodu** [comment] 2020-02-04 10:56
Duplicate of #1011

**Closed by jkodu** 2020-02-04 10:56 UTC
Labels: Discussion, Rule, Rule Update
