### ISSUE TITLE
Lang verification (bf051a and de46e4) extends beyond requirements

### ISSUE THREAD

**Issue by tombrunet** [act-rules/act-rules.github.io#1087] opened 2019-12-18 01:53 UTC
The ACT rules state:
> A text string following the syntax as defined in BCP 47, with a primary language subtag from the language subtag registry.

https://www.w3.org/WAI/WCAG21/Techniques/html/H58 states:
> Check that the value of the lang attribute conforms to BCP 47: Tags for the Identification of Languages or its successor

While I agree that the ACT rule provides a better end result, verification against the language subtag registry isn't strictly noted by WCAG. 

At the top-level, BCP 47 expression is:
```
language = 2*3ALPHA            ; shortest ISO 639 code
           ["-" extlang]       ; sometimes followed by
                               ; extended language subtags
           / 4ALPHA            ; or reserved for future use
           / 5*8ALPHA          ; or registered language subtag
```
As such, de46e4 Failed example 1 _technically_ passes WCAG since `dutch` is well-formed with respect to 5*8ALPHA . 

So, how do you argue that WCAG requires the **primary language subtag from the language subtag registry** piece? Are you arguing that's the successor to BCP 47?

**Comment by WilcoFiers** [comment] 2020-01-20 11:55
Looking into this a little, I actually think that technique is a little wrong. Or at least, it's doesn't ask quite the right thing. I'll create an issue for AG to handle this instead. WDYT?

**Comment by jkodu** [comment] 2020-02-04 10:54
Duplicate of https://github.com/w3c/wcag/issues/1028

**Comment by sarahbrunet** [comment] 2020-02-04 15:35
@jkodu Not a dupe. w3c/wcag#1028 argues that WCAG's lang requirement are more strict than necessary. This issue is that the ACT rules are even more strict than WCAG. So, w3c/wcag#1028 is more of an argument for this issue as opposed to a dupe.

**Comment by tombrunet** [comment] 2020-02-04 18:04
@jkodu Not a dupe. w3c/wcag#1028 argues that WCAG's lang requirement are more strict than necessary. This issue is that the ACT rules are even more strict than WCAG. So, w3c/wcag#1028 is more of an argument for this issue as opposed to a dupe. <Sorry - wrong id first time>

**Comment by jkodu** [comment] 2020-07-08 22:26
@tombrunet I agree. Conversations are being had in the ACT TF to find a solution for this & how best to reflect the same in ACT Rules. In view of that, I will close this issue & updates will follow based on conclusion reached on this subject with ACT TF. Thank you.

**Closed by jkodu** 2020-07-08 22:26 UTC
Labels: Agenda item

**Comment by tombrunet** [comment] 2021-04-19 15:10
@jeeyyy Where did this end up? Mis-alignment between rules and requirements seems problematic to me.
