### ISSUE TITLE
Visible label is part of accessible name (2ee8b8): Non-text content is ambiguous

### ISSUE THREAD

**Issue by kasperisager** [act-rules/act-rules.github.io#377] opened 2018-12-17 14:31 UTC
As https://auto-wcag.github.io/auto-wcag/rules/SC2-5-3-label-content-name-mismatch.html makes use of the term "non-text content" within its applicability and lacks an unambiguous definition of this term, it is not currently a valid ACT rule. We currently have a definition of text content (https://auto-wcag.github.io/auto-wcag/pages/glossary/text-content.html) though given that definition then the following case would be classified as having visible text content:

```html
 <button aria-label="close">X</button>
```

This case is however supposed to be inapplicable to the rule and therefore not be classified as having visible text content.

**Comment by kasperisager** [comment] 2018-12-17 14:32
Summoning @ShadowBB.

**Comment by annethyme** [comment] 2019-03-07 14:06
Handling it in https://github.com/auto-wcag/auto-wcag/pull/430

**Comment by Jym77** [comment] 2020-05-15 09:22
Reopening issue since #452 that was partly tackling it has been closed.

**Comment by WilcoFiers** [comment] 2020-08-26 12:08
This issue is a duplicate of #1254, and will soon be addressed.

**Closed by WilcoFiers** 2020-08-26 12:08 UTC
Labels: Rule, Rule Update
