### ISSUE TITLE
ARIA state or property has valid value' problems with applicability [6a7281]

### ISSUE THREAD

**Issue by dd8** [act-rules/act-rules.github.io#1205] opened 2020-03-04 08:12 UTC
According to the Accessibility Requirements Mapping 'ARIA state or property has valid value' is checking ARIA validity, but inapplicable example 3 is invalid per the ARIA spec:

https://act-rules.github.io/rules/6a7281#inapplicable-example-3

https://www.w3.org/TR/wai-aria-1.1/#aria-checked

The W3 validator flags this as invalid. 

This affects the applicability which excludes invalid ARIA attributes like `aria-checked` and `aria-checked=''` (but not `aria-checked='  '`)

There is a custom element in the examples, but the HTML spec makes a distinction between HTML elements and custom elements, and the applicability only includes HTML and SVG elements:
https://html.spec.whatwg.org/multipage/custom-elements.html#custom-elements

Custom element applicability be fixed by changing 
> and that is specified on an HTML or SVG element

to
> and that is specified on an HTML, SVG or custom element

**Comment by Jym77** [comment] 2020-03-10 13:22
1. Yes, I agree that no value or empty value is as invalid as any other bad value. We should probably update the applicability to any `aria-*` attribute and check that it has a value and that value is correct. Or add another rule to check that `aria-*` attributes have non-empty value.

2. I don't thing we really define "HTML element" anywhere, so it is not clear whether custom elements (used in HTML) are considered HTML elements or not… Nonetheless, this is the only custom element we use (AFAICT) and the example should maybe just be removed…

**Comment by kasperisager** [comment] 2020-03-20 08:54
Your point about "HTML element" is a good one. My interpretation is "element in the HTML namespace" which would include custom elements that extend from `HTMLElement`, either because they're autonomous or because they extend built-in elements: https://html.spec.whatwg.org/multipage/custom-elements.html#custom-element. This issue is however evidence of that interpretation not being the only valid one so there's an ambiguity that needs to be resolved.

**Comment by WilcoFiers** [comment] 2020-04-23 08:45
Talked about this in the CG call. While not ideal, this is allowed in ARIA, we're going to add a note to the example explaining this is invalid HTML and that this will result in the default value.

**Comment by WilcoFiers** [comment] 2020-05-12 11:31
The ARIA props part of this has been merged. The other part of this issue is a duplicate of https://github.com/act-rules/act-rules.github.io/issues/459, so I'm closing this one.

**Closed by WilcoFiers** 2020-05-12 11:31 UTC
Labels: Agenda item
