### ISSUE TITLE
Some unit tests still have other non-related issues in test

### ISSUE THREAD

**Issue by mraccess77** [act-rules/act-rules.github.io#1712] opened 2021-09-20 19:00 UTC
Unit tests
 https://act-rules.github.io/testcases/b40fd1/264074a97f3844f1c90b88997a5cacf38f5ba6c2.html 
https://act-rules.github.io/testcases/b40fd1/3d998f21a9619333a475d5a7449873a76e547292.html
https://act-rules.github.io/testcases/b40fd1/b889767b4d1f2fe358acea887c9ad39c6974cd2f.html
have an html element with no lang attribute.

**Comment by carlosapaduarte** [comment] 2021-09-23 07:57
@mraccess77 Thanks for raising this issue. This is going to be addressed as part of the migration to the WAI website. The migration process will try to fix this type of accessibility violations in the examples automatically when producing the test cases.

**Comment by WilcoFiers** [comment] 2021-09-28 09:20
This issue seems like a duplicate of #1165. I'm going to close it, but know we're working to address the issues.

**Closed by WilcoFiers** 2021-09-28 09:20 UTC
