### ISSUE TITLE
Visible label (2ee8b8) inconsistency between pass and inapplicable

### ISSUE THREAD

**Issue by tombrunet** [act-rules/act-rules.github.io#1618] opened 2021-05-25 15:58 UTC
Rule: https://act-rules.github.io/rules/2ee8b8
This is regarding "Passed example 6" (Pass6) and "Inapplicable example 4" (NA4). NA4 notes that it doesn't apply because the content is an image and not visible text. However, the argument that the rule passes for Pass6 is basically the same - it's not visible text. This seems inconsistent. If the content renders as an image and not text, is it a pass, or is it inapplicable?

Note that both situations /can/ result in rendered text, which makes the situation more difficult. If the font fails to load or isn't supported for Pass6, or if the image fails to load for NA4, the text will display in its place. In this scenario, both of these would be a failure.

**Comment by Jym77** [comment] 2021-06-17 11:19
I think the examples are fairly different and this is already handled in the Applicability.

The Applicability is to elements that have "visible text content" which in turn refers to "visible text nodes". The button of PE6 has a text node (even though it is rendered weirdly, it is nonetheless a text node, e.g. you can `.innerText` on the button and get `"search"`). The image of NA4 doesn't have a text node. The alt text is set via an attribute, not a text node.

So, I think that in its current state the rule is indeed applicable to PE6 but not to NA4. Of course, descriptions can always be improved.

**Comment by tombrunet** [comment] 2021-06-17 14:20
But, can't really tell the difference from the accessibility tree:
Pass6:
* button "Find"
  * text "search"
  
NA4:
* link "W3C homepage"
  * img "w3c logo" 
  
If the image doesn't load, it shows as:
![image](https://user-images.githubusercontent.com/19577713/122413305-e10aa480-cf4b-11eb-8445-4be0214fe4ce.png)

It's confusing to say that this isn't visible text content. To add to it, what if I use `object` for the image where the alt is a descendant text node, and again is visible if the image doesn't load? It feels like a pretty arbitrary distinction to exclude img.

**Comment by Jym77** [comment] 2021-06-24 10:37
Discussed in the CG call today. Was cut short by time, so no real decision was taken (yet).

It seems that the common opinion was that the current situation is OK, and that it is also OK to be Inapplicable for
```
<img src="inexistant.jpg" alt="Foo" />
```
(which will always show the alt text), even though it is very similar to a normal link with text…

Some arguments:
* Even if the (shown) alt text is considered as a label, in order to fail the SC we'd need a different accessible name. This can be done with `<img src="foo.jpg" alt="foo" "aria-label="bar" />` (since `aria-label` takes precedence over `alt`); but it seems to be a very rare corner case to have these situations in the wild. Making the rule more complex just to move some cases from Inapplicable to Passed is not really worth the effort…
* "Inapplicable" as an outcome doesn't mean anything whether the page satisfies or not the SC, so it is OK to keep the rules simple and not handle all the cases. Obviously not ideal, but still OK.
* It feels like the rules (in general) shouldn't care about partial loading of the pages. Without it being an explicit requirement, partial loading of a page could lead to so many problems (e.g. missing scripts, CSS, …) that most rules would break that way, so trying to handle that inside the rules is likely not doable.
* Additionally, if the image is always missing (wrong URL, …) it feels like this would be spotted early during QA process and be flagged as a generic problem, not just an accessibility one, making it even less appealing to try and handle that inside the rule. Testers might just try reloading the page, or report that the page couldn't be fully tested due to a missing image.

**Comment by WilcoFiers** [comment] 2021-07-08 14:46
Decision from the group: Put some information in the background about images that fail to load.

**Comment by Jym77** [comment] 2021-08-19 12:17
@tombrunet Does #1691 (new assumption) ease your concerns?

**Comment by tombrunet** [comment] 2021-08-19 13:20
@Jym77 It's a good assumption to list, but still doesn't explain for me why one of these is N/A and the other is Pass. To me, they are two different ways of defining an image, and two ways of associating non-visible text with that image.

For us, the rule triggers on the node that's interactive. If that interactive thing has no visible text, is that a Pass or Not Applicable? The distinction that it behaves differently because there's a text node is pretty arbitrary. What if I had an `object` whose alt text is a nested text node? By the above logic, I'd consider that a pass, but then I'm further singling out `img` as a weird corner case.

Overall, the concern is that it's a distinction that can be made in code, but very difficult to explain to a user. They look the same, they sound the same, they have similar accessibility API outputs, they behave the same, but one passes and the other's not applicable? Why?

**Comment by Jym77** [comment] 2021-08-19 14:35
@tombrunet Part of the answer is that there is no real difference between "Passed" and "Inapplicable": https://act-rules.github.io/pages/implementations/mapping/#automated-mapping
What's important is that it is not "Failed" (i.e. we do not see an accessibility issue for sure on that example).

So, if a tool choses to have Pass6 as "Inapplicable" rather than "Passed" (or NA4 as "Passed" instead of "Inapplicable"), it will still be a "correct implementation" as far as we are concerned. It's up to tool vendors to decide what they think makes more sense to show to their users. As far as ACT rules are concerned, what's important is to agree that something is failing the SC for sure. It's OK for a page to be Inapplicable even though it is failing the SC, rules are more restricted than SC.

Note that such choices in tools do happen. See for example [Alfa's report of "Image has non-empty accessible name"](https://act-rules.github.io/implementation/alfa#id-23a2a8). In Alfa, we decided that it makes more sense to have presentational images as "Inapplicable" rather than "Passed". This doesn't prevent us from agreeing on what fails the SC for sure and having a valid implementation. The important point is that whatever tool a end user decides to use, they'll get the same things flagged as "bad".

---
The fact that "Inapplicable" and "Passed" are more or less equivalent comes from the strong design choice of having rules that spot errors, rather than rules that give "validation badges". A page that fails no ACT rule may still have a lot of WCAG violations. ACT rules are designed to spot guaranteed errors

---
So, I guess the distinction is indeed arbitrary but does allow a clean technical separation which automated tools can rely one. It might be harder for manual testers to spot (and respect) that distinction, but that won't prevent the testing methodology to be a correct implementation of the rule. On the other hand, tweaking the rule to make Pass6 Inapplicable (or NA4 Passing) might end up in something that is not automatable (e.g. deciding whether text or image is rendered in Pass6). So we kinda want to stick with the automatable version as automation is also one of our goal.

---
Of course, I'd be happy to put the issue back on the Agenda for another CG call. I'm however a bit concerned that if you cannot be present to discuss the case, the same people will likely end up reaching the same conclusion.

**Comment by tombrunet** [comment] 2021-08-19 18:00
I'd say that detecting that the specified font renders an icon instead of text is likely the hardest part of this whole rule. If you can automate detection of that not being a failure, then assigning it as Pass vs. N/A should be easy.
As for calls, the kids just started school yesterday here, and schedules are starting to settle. I may actually be able to start getting involved.

**Comment by WilcoFiers** [comment] 2021-08-24 09:58
@tombrunet The ACT TF had a fairly lengthy discussion about passed examples 5 & 6 too. The problem is that there is no objective way to say which glyph is used as text, and which is used as an icon. The ACT Rules Format only allows us to put objective tests in the applicability, so there was no way for us to say those were inapplicable, even though logically, they probably both should be.

We've seen that problem in a few rules, which has started a conversation  of us potentially letting go of this "applicability must be objective" requirement in the next version of the ACT rules format. For now, this is an artefact of how the ACT Rules Format works, and something we likely will revisit in the future.


As for checking what an image or text would be like if the image or font didn't load... this is currently out of scope of ACT rules. ACT rules test content in the given state. The only rules that test multiple states are rules where multiple states matter for conformance, such as what the states are before and after a hover. Testing state is something we need to get better at too. We've experimented with a few things in the past, and it is something I would like to see us put some effort into in the next version of the ACT Rules Format.

**Comment by tombrunet** [comment] 2021-08-24 14:39
Just to be clear, we're going on this part of the "applicability" to make the distinction:
> The element has visible text content;

So the distinction between pass and N/A isn't non-text content vs text content, but rather does the widget have any non-zero length text nodes. It's more confusing to me that way, but it's at least consistent.

I think I would have preferred in that case to get rid of that in the applicability so that the rule is applicable for all widgets, and then allow all widgets with no text content to pass this rule.

So, what about an `svg` with a `title` alt text? I believe by the current definition that would be a pass, correct? It further singles out `img[alt]` as an oddity for this rule.

**Closed** 2021-11-11 14:55 UTC
